name: Preview

on:
  pull_request:
    types: [labeled]

env:
  TELEGRAPH_AUTHOR_URL: ${{ github.event.pull_request.html_url }}
  TELEGRAPH_TITLE: ${{ github.event.number }}

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'wait-preview') && github.event.sender.login == 'gabbhack' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -U pip virtualenv poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Deploy preview to Telegra.ph
      run: |
        python main.py preview >> $GITHUB_ENV
    - uses: actions/github-script@v5
      with:
        script: |
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Preview: ${process.env.PAGE_URL}`
          })
          await github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'wait-preview'
          });
