name: Test

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -U pip virtualenv poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Test
      run: |
        python main.py
